# Generated by Django 2.2.2 on 2021-01-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WangtoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(auto_now_add=True, verbose_name='存储有效期')),
                ('capacity', models.BigIntegerField(default=0, verbose_name='储存容量')),
                ('now_data_size', models.BigIntegerField(default=0, verbose_name='现有总数据大小')),
                ('data_money', models.PositiveIntegerField(default=0, verbose_name='剩余流量金额')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=30, verbose_name='数据名称')),
                ('data_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('state', models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoDataAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inspect', models.BooleanField(default=False, verbose_name='是否审核')),
                ('is_operate', models.BooleanField(default=False, verbose_name='是否标注')),
                ('data_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('inspect_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('operate_time', models.DateTimeField(blank=True, null=True, verbose_name='标注时间')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDataAllocation', to='WEBAPI.WangtoData', verbose_name='数据名')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set_name', models.CharField(max_length=30, verbose_name='数据集名称')),
                ('data_num', models.PositiveIntegerField(default=0, verbose_name='数据量')),
                ('state', models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoDataSetAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDataSetAllocation', to='WEBAPI.WangtoDataSet', verbose_name='数据集名')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='wangto用户', max_length=20, verbose_name='昵称')),
                ('account', models.CharField(max_length=11, verbose_name='手机号/登录账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('state', models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态')),
                ('identity', models.CharField(choices=[('leader', '项目负责人'), ('admin', '管理员')], max_length=6, verbose_name='身份')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('account_msg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEBAPI.WangtoAccount', verbose_name='账户数据')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_leader', to='WEBAPI.WangtoUser', verbose_name='创建者')),
                ('information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEBAPI.WangtoUserInfo', verbose_name='其他信息')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('data', models.ManyToManyField(related_name='WangtoProject', through='WEBAPI.WangtoDataAllocation', to='WEBAPI.WangtoData', verbose_name='所用数据')),
                ('data_set', models.ManyToManyField(related_name='WangtoProject', through='WEBAPI.WangtoDataSetAllocation', to='WEBAPI.WangtoDataSet', verbose_name='所用数据集')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoPaymentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WangtoPaymentRecords', to='WEBAPI.WangtoUser', verbose_name='所有者')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='wangto标注员', max_length=20, verbose_name='昵称')),
                ('account', models.CharField(max_length=11, verbose_name='手机号/登录账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('state', models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_operator', to='WEBAPI.WangtoUser', verbose_name='拥有者')),
                ('data', models.ManyToManyField(related_name='WangtoOperator', through='WEBAPI.WangtoDataAllocation', to='WEBAPI.WangtoData', verbose_name='分配任务')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WangtoOperator', to='WEBAPI.WangtoUser', verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='WangtoInspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default='wangto审核员', max_length=20, verbose_name='昵称')),
                ('account', models.CharField(max_length=11, verbose_name='手机号/登录账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('state', models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_inspector', to='WEBAPI.WangtoUser', verbose_name='创拥有者')),
                ('data', models.ManyToManyField(related_name='WangtoInspector', through='WEBAPI.WangtoDataAllocation', to='WEBAPI.WangtoData', verbose_name='分配任务')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WangtoInspector', to='WEBAPI.WangtoUser', verbose_name='创建者')),
            ],
        ),
        migrations.AddField(
            model_name='wangtodatasetallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDataSetAllocation', to='WEBAPI.WangtoProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='wangtodataallocation',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDataAllocation', to='WEBAPI.WangtoInspector', verbose_name='审核员'),
        ),
        migrations.AddField(
            model_name='wangtodataallocation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDataAllocation', to='WEBAPI.WangtoOperator', verbose_name='标注员'),
        ),
        migrations.AddField(
            model_name='wangtodataallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDataAllocation', to='WEBAPI.WangtoProject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='wangtodata',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WangtoDate', to='WEBAPI.WangtoDataSet', verbose_name='所属数据集'),
        ),
    ]
