# Generated by Django 3.1.4 on 2021-01-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wangtouser',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_leader', to='WEBAPI.wangtouser', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='identity',
            field=models.CharField(choices=[('leader', '项目负责人'), ('admin', '管理员')], max_length=6, verbose_name='身份'),
        ),
    ]
