# Generated by Django 2.2.2 on 2021-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPI', '0003_auto_20210105_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wangtodata',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtodataset',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtoinspector',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtooperator',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='identity',
            field=models.CharField(choices=[('leader', '项目负责人'), ('admin', '管理员')], max_length=6, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
    ]
