# Generated by Django 3.1.4 on 2021-01-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPI', '0005_auto_20210106_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wangtodata',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtodataset',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtoinspector',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtooperator',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
    ]
