# Generated by Django 3.1.4 on 2021-01-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPI', '0007_auto_20210106_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='wangtoinspector',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_inspector', to='WEBAPI.wangtouser', verbose_name='创拥有者'),
        ),
        migrations.AddField(
            model_name='wangtooperator',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_operator', to='WEBAPI.wangtouser', verbose_name='拥有者'),
        ),
        migrations.AlterField(
            model_name='wangtodata',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtodataset',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtoinspector',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtooperator',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='identity',
            field=models.CharField(choices=[('leader', '项目负责人'), ('admin', '管理员')], max_length=6, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='state',
            field=models.CharField(choices=[('active', '激活'), ('invalid', '弃用')], max_length=7, verbose_name='状态'),
        ),
    ]
