# Generated by Django 2.2.2 on 2021-01-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPI', '0008_auto_20210106_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wangtodata',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtodataset',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtoinspector',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtooperator',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='identity',
            field=models.CharField(choices=[('admin', '管理员'), ('leader', '项目负责人')], max_length=6, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='wangtouser',
            name='state',
            field=models.CharField(choices=[('invalid', '弃用'), ('active', '激活')], max_length=7, verbose_name='状态'),
        ),
    ]
